sudo: required
services:
    - docker

before_install:
    - docker build -t zhilong1115/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run zhilong1115/react-test npm test -- --coverage

after_success:
    - docker build -t zhilong1115/multi-client ./client
    - docker build -t zhilong1115/multi-nginx ./nginx
    - docker build -t zhilong1115/multi-server ./server
    - docker build -t zhilong1115/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push zhilong1115/multi-client
    - docker push zhilong1115/multi-nginx
    - docker push zhilong1115/multi-server
    - docker push zhilong1115/multi-worker